import { EdgeSlot, MilpaSlot } from "../../src/classes/slots";

export const EMPTY_MILPA_SLOT = new MilpaSlot([]);
export const EMPTY_EDGE_SLOT = new EdgeSlot([]);

export const EMPTY_MILPA = [
  EMPTY_MILPA_SLOT,
  EMPTY_MILPA_SLOT,
  EMPTY_MILPA_SLOT,
  EMPTY_MILPA_SLOT,
  EMPTY_MILPA_SLOT,
  EMPTY_MILPA_SLOT,
  EMPTY_MILPA_SLOT,
  EMPTY_MILPA_SLOT,
  EMPTY_MILPA_SLOT,
  EMPTY_MILPA_SLOT,
  EMPTY_MILPA_SLOT,
  EMPTY_MILPA_SLOT,
  EMPTY_MILPA_SLOT,
  EMPTY_MILPA_SLOT,
  EMPTY_MILPA_SLOT,
  EMPTY_MILPA_SLOT,
];

export const EMPTY_EDGE = [
  EMPTY_EDGE_SLOT,
  EMPTY_EDGE_SLOT,
  EMPTY_EDGE_SLOT,
  EMPTY_EDGE_SLOT,
  EMPTY_EDGE_SLOT,
  EMPTY_EDGE_SLOT,
  EMPTY_EDGE_SLOT,
  EMPTY_EDGE_SLOT,
  EMPTY_EDGE_SLOT,
  EMPTY_EDGE_SLOT,
  EMPTY_EDGE_SLOT,
  EMPTY_EDGE_SLOT,
  EMPTY_EDGE_SLOT,
  EMPTY_EDGE_SLOT,
  EMPTY_EDGE_SLOT,
  EMPTY_EDGE_SLOT,
];
